apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-hopper-ui
  labels:
    app: {{.Release.Name}}-hopper-ui
spec:
  ports:
    - port: 80
  selector:
    app: {{.Release.Name}}-hopper-ui
    tier: frontend
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{.Release.Name}}-hopper-ui-ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"

spec:
  tls:
  - hosts:
    - {{.Values.UiHost}}
    secretName: {{.Release.Name}}-hopper-ui-tls
  rules:
    - host: {{.Values.UiHost}}
      http:
        paths:
        - backend:
            serviceName: {{.Release.Name}}-hopper-ui
            servicePort: 80
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{.Release.Name}}-hopper-ui
  labels:
    app: {{.Release.Name}}-hopper-ui
spec:
  replicas: {{ .Values.UiReplicas }}
  selector:
    matchLabels:
      app: {{.Release.Name}}-hopper-ui
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-hopper-ui
        tier: frontend
    spec:
      containers:
      - image: lucaschimweg/hopper-ui:dev-27
        name: {{.Release.Name}}-hopper-ui
        ports:
        - containerPort: 80
          name: {{.Release.Name}}-hopper-api
        env:
        - name: HOPPER_API_URL
          value: https://{{.Values.ApiHost}}/v1
        - name: HOPPER_LOGIN_URL
          value: {{.Values.LoginUrl}}
